import ActorNode from "./ActorNode";
import AnimationInstance from "./AnimationInstance";
import Actor from "./Actor";
export default class ActorArtboard {
    _Actor: any;
    _Components: any[];
    _Nodes: any[];
    _RootNode: ActorNode;
    _Drawables: any[];
    _Animations: any[];
    _IsImageSortDirty: boolean;
    _Order: any;
    _IsDirty: boolean;
    _DirtDepth: number;
    _Name: string;
    _Origin: any;
    _Translation: any;
    _Color: any;
    _ClipContents: boolean;
    _Width: number;
    _Height: number;
    _ClippingPath: any;
    constructor(actor: Actor);
    readonly name: string;
    readonly width: number;
    readonly height: number;
    readonly origin: string;
    readonly translation: any;
    readonly color: any;
    readonly color8: any;
    readonly clipContents: boolean;
    readonly root: ActorNode;
    readonly actor: any;
    addDependency(a: any, b: any): boolean;
    sortDependencies(): boolean;
    addDirt(component: any, value: any, recurse: any): boolean;
    update(): boolean;
    resolveHierarchy(): void;
    dispose(graphics: any): void;
    advance(seconds: any): void;
    draw(graphics: any): void;
    getNode(name: any): any;
    readonly animations: any[];
    getAnimation(name: any): any;
    getAnimationInstance(name: any): AnimationInstance;
    makeInstance(): ActorArtboard;
    artboardAABB(): Float32Array;
    computeAABB(): Float32Array;
    copy(artboard: any): void;
    initialize(graphics: any): void;
}
